; terminals
ref_start = "(("
ref_end = "))"

page_start = "[["
page_end = "]]"

func_start = "{{"
func_end = "}}"

code_start = "```"
code_end = "```"

id = 9ALPHA ;hashid for blocks
text = VCHAR

<page> = "[[" text* <page> text* "]]"
<ref> = "((" id "))"

<cond> = "{" ("and" / "or" / "not") (<page> | <ref>)+ "}" / "{between:" <date> <date>"}"
<query_cond> = "{" ("and" / "or" / "not") (<page> | <ref>)* <cond> (<page> | <ref>)* "}"

<query> = func_start ("query" / "[[query]]") <query_cond> func_end
